services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: spy-cats-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped